/**
 * Official WC2026 group stage schedule — all times ET (UTC-4).
 *
 * Maps bracket.ts match IDs (G0..G71) to their kickoff date/time.
 * Match IDs generated by generateGroupMatches() in bracket order:
 *   G0  = Group A MD1: 1v2 = Mexico vs South Africa
 *   G1  = Group A MD1: 4v3 = Czech Republic vs South Korea
 *   G2  = Group A MD2: 1v3 = Mexico vs South Korea
 *   G3  = Group A MD2: 4v2 = Czech Republic vs South Africa
 *   G4  = Group A MD3: 1v4 = Mexico vs Czech Republic
 *   G5  = Group A MD3: 2v3 = South Africa vs South Korea
 *   ...same pattern for each group
 */
export const GROUP_SCHEDULE: Record<string, string> = {
	// === Group A ===
	// Thu Jun 11
	G0: "2026-06-11T15:00:00-04:00", // Mexico vs South Africa
	G1: "2026-06-11T22:00:00-04:00", // Czech Republic vs South Korea
	// Thu Jun 18
	G2: "2026-06-18T21:00:00-04:00", // Mexico vs South Korea
	G3: "2026-06-18T12:00:00-04:00", // Czech Republic vs South Africa
	// Wed Jun 24
	G4: "2026-06-24T21:00:00-04:00", // Mexico vs Czech Republic
	G5: "2026-06-24T21:00:00-04:00", // South Africa vs South Korea

	// === Group B ===
	// Fri Jun 12
	G6: "2026-06-12T15:00:00-04:00", // Canada vs Bosnia
	G7: "2026-06-13T15:00:00-04:00", // Switzerland vs Qatar (PDF: Qatar vs Switzerland)
	// Thu Jun 18
	G8: "2026-06-18T18:00:00-04:00", // Canada vs Qatar
	G9: "2026-06-18T15:00:00-04:00", // Switzerland vs Bosnia
	// Wed Jun 24
	G10: "2026-06-24T15:00:00-04:00", // Canada vs Switzerland
	G11: "2026-06-24T15:00:00-04:00", // Bosnia vs Qatar

	// === Group C ===
	// Sat Jun 13
	G12: "2026-06-13T18:00:00-04:00", // Brazil vs Morocco
	G13: "2026-06-13T21:00:00-04:00", // Scotland vs Haiti (PDF: Haiti vs Scotland)
	// Fri Jun 19
	G14: "2026-06-19T20:30:00-04:00", // Brazil vs Haiti
	G15: "2026-06-19T18:00:00-04:00", // Scotland vs Morocco
	// Wed Jun 24
	G16: "2026-06-24T18:00:00-04:00", // Brazil vs Scotland
	G17: "2026-06-24T18:00:00-04:00", // Morocco vs Haiti

	// === Group D ===
	// Fri Jun 12
	G18: "2026-06-12T21:00:00-04:00", // USA vs Paraguay
	G19: "2026-06-14T00:00:00-04:00", // Turkey vs Australia (PDF: Australia vs Turkey)
	// Fri Jun 19
	G20: "2026-06-19T15:00:00-04:00", // USA vs Australia
	G21: "2026-06-19T23:00:00-04:00", // Turkey vs Paraguay
	// Thu Jun 25
	G22: "2026-06-25T22:00:00-04:00", // USA vs Turkey
	G23: "2026-06-25T22:00:00-04:00", // Paraguay vs Australia

	// === Group E ===
	// Sun Jun 14
	G24: "2026-06-14T13:00:00-04:00", // Germany vs Curacao
	G25: "2026-06-14T19:00:00-04:00", // Ecuador vs Ivory Coast (PDF: Ivory Coast vs Ecuador)
	// Sat Jun 20
	G26: "2026-06-20T16:00:00-04:00", // Germany vs Ivory Coast
	G27: "2026-06-20T20:00:00-04:00", // Ecuador vs Curacao
	// Thu Jun 25
	G28: "2026-06-25T16:00:00-04:00", // Germany vs Ecuador
	G29: "2026-06-25T16:00:00-04:00", // Curacao vs Ivory Coast

	// === Group F ===
	// Sun Jun 14
	G30: "2026-06-14T16:00:00-04:00", // Netherlands vs Japan
	G31: "2026-06-14T22:00:00-04:00", // Tunisia vs Sweden (PDF: Sweden vs Tunisia)
	// Sat Jun 20
	G32: "2026-06-20T13:00:00-04:00", // Netherlands vs Sweden
	G33: "2026-06-21T00:00:00-04:00", // Tunisia vs Japan (PDF: Tunisia vs Japan — midnight)
	// Thu Jun 25
	G34: "2026-06-25T19:00:00-04:00", // Netherlands vs Tunisia
	G35: "2026-06-25T19:00:00-04:00", // Japan vs Sweden

	// === Group G ===
	// Mon Jun 15
	G36: "2026-06-15T15:00:00-04:00", // Belgium vs Egypt
	G37: "2026-06-15T21:00:00-04:00", // New Zealand vs Iran (PDF: Iran vs New Zealand)
	// Sun Jun 21
	G38: "2026-06-21T15:00:00-04:00", // Belgium vs Iran
	G39: "2026-06-21T21:00:00-04:00", // New Zealand vs Egypt
	// Fri Jun 26
	G40: "2026-06-26T23:00:00-04:00", // Belgium vs New Zealand
	G41: "2026-06-26T23:00:00-04:00", // Egypt vs Iran

	// === Group H ===
	// Mon Jun 15
	G42: "2026-06-15T12:00:00-04:00", // Spain vs Cape Verde
	G43: "2026-06-15T18:00:00-04:00", // Uruguay vs Saudi Arabia (PDF: Saudi Arabia vs Uruguay)
	// Sun Jun 21
	G44: "2026-06-21T12:00:00-04:00", // Spain vs Saudi Arabia
	G45: "2026-06-21T18:00:00-04:00", // Uruguay vs Cape Verde
	// Fri Jun 26
	G46: "2026-06-26T20:00:00-04:00", // Spain vs Uruguay
	G47: "2026-06-26T20:00:00-04:00", // Cape Verde vs Saudi Arabia

	// === Group I ===
	// Tue Jun 16
	G48: "2026-06-16T15:00:00-04:00", // France vs Senegal
	G49: "2026-06-16T18:00:00-04:00", // Norway vs Iraq (PDF: Iraq vs Norway)
	// Mon Jun 22
	G50: "2026-06-22T17:00:00-04:00", // France vs Iraq
	G51: "2026-06-22T20:00:00-04:00", // Norway vs Senegal
	// Fri Jun 26
	G52: "2026-06-26T15:00:00-04:00", // France vs Norway
	G53: "2026-06-26T15:00:00-04:00", // Senegal vs Iraq

	// === Group J ===
	// Tue Jun 16
	G54: "2026-06-16T21:00:00-04:00", // Argentina vs Algeria
	G55: "2026-06-17T00:00:00-04:00", // Jordan vs Austria (PDF: Austria vs Jordan — midnight)
	// Mon Jun 22
	G56: "2026-06-22T13:00:00-04:00", // Argentina vs Austria
	G57: "2026-06-22T23:00:00-04:00", // Jordan vs Algeria
	// Sat Jun 27
	G58: "2026-06-27T22:00:00-04:00", // Argentina vs Jordan
	G59: "2026-06-27T22:00:00-04:00", // Algeria vs Austria

	// === Group K ===
	// Wed Jun 17
	G60: "2026-06-17T13:00:00-04:00", // Portugal vs DR Congo
	G61: "2026-06-17T22:00:00-04:00", // Colombia vs Uzbekistan (PDF: Uzbekistan vs Colombia)
	// Tue Jun 23
	G62: "2026-06-23T13:00:00-04:00", // Portugal vs Uzbekistan
	G63: "2026-06-23T22:00:00-04:00", // Colombia vs DR Congo
	// Sat Jun 27
	G64: "2026-06-27T19:30:00-04:00", // Portugal vs Colombia
	G65: "2026-06-27T19:30:00-04:00", // DR Congo vs Uzbekistan

	// === Group L ===
	// Wed Jun 17
	G66: "2026-06-17T16:00:00-04:00", // England vs Croatia
	G67: "2026-06-17T19:00:00-04:00", // Panama vs Ghana (PDF: Ghana vs Panama)
	// Tue Jun 23
	G68: "2026-06-23T16:00:00-04:00", // England vs Ghana
	G69: "2026-06-23T19:00:00-04:00", // Panama vs Croatia
	// Sat Jun 27
	G70: "2026-06-27T17:00:00-04:00", // England vs Panama
	G71: "2026-06-27T17:00:00-04:00", // Croatia vs Ghana
};
